Update apt before installing any packages
This ensures that all `apt::ppa` and `apt::source` resources are applied and
`apt-get update` is run before installing any packages that might (secretly)
depend on them. This came up after removing the PPAs from bootstrap scripts.
Fixes a particular problem with Nginx, but probably affects many other
packages:
```
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install nginx=1.4.4-4~precise0' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.4.4-4~precise0' for 'nginx' was not found

Error: /Stage[main]/Nginx::Server/Package[nginx]/ensure: change from purged to 1.4.4-4~precise0 failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-ye
s install nginx=1.4.4-4~precise0' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.4.4-4~precise0' for 'nginx' was not found
```